In [11]:
import xarray as xr

In [33]:
# strings are immutable and indexing is non-inclusive

str_arr = 'hello world'
str_arr[0:5]      # works as expected

'hello'

In [35]:
str_arr[0] = 'H'  # gives an error (Python requires you to define a new string)

TypeError: 'str' object does not support item assignment

In [38]:
# equalities are generally pointers unless .copy() is specified

mod_arr = xr.DataArray(np.arange(5))
mod_arr

<xarray.DataArray (dim_0: 5)>
array([0, 1, 2, 3, 4])
Dimensions without coordinates: dim_0

In [39]:
mod_too = mod_arr
mod_arr[0] = 4
mod_too   # surprising!

<xarray.DataArray (dim_0: 5)>
array([4, 1, 2, 3, 4])
Dimensions without coordinates: dim_0

In [42]:
mod_arr = xr.DataArray(np.arange(5))
mod_too = mod_arr.copy()
mod_arr[0] = 4
mod_too   # we needed to make that copy to maintain independent variable

<xarray.DataArray (dim_0: 5)>
array([0, 1, 2, 3, 4])
Dimensions without coordinates: dim_0